apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs
  namespace: services
  labels:
    app: gtfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtfs
  template:
    metadata:
      labels:
        app: gtfs
    spec:
      containers:
        - name: gtfs
          image: docker.io/vilibalchev5/gtfs:86300b349e5893247fb7924a498e13240653b51f
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health/
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
