apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs
  namespace: services
  labels:
    app: gtfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtfs
  template:
    metadata:
      labels:
        app: gtfs
    spec:
      containers:
        - name: gtfs
          image: ghcr.io/tues-2026-pbl-11-klas/gtfs:e1f1089fb0ed7db97dcf338d5ef90225dd658642
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health/
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
