apiVersion: v1
kind: Service
metadata:
  name: gtfs-service
  namespace: gtfs
  labels:
    app: gtfs
spec:
  selector:
    app: gtfs
  ports:
    - name: http
      port: 5000
      targetPort: 5000
