apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: auth
          image: docker.io/vilibalchev5/auth-new:7da140e7be2b3f1b93ea7a6fae4598de554e7252