apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: auth
          image: docker.io/vilibalchev5/auth-new:4cc0df7a795c29c352781be8418cb8a6703f3762