apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: auth
          image: docker.io/vilibalchev5/auth-new:5f97218a40724f709580bba8ae60a93a6cfc5fd1