apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: gtfs
          image: docker.io/vilibalchev5/gtfs:e77add7a81e1c0d648ffe6ece9fb0a69d3422679