apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: gtfs
          image: docker.io/vilibalchev5/gtfs:1773ae38f7b841a72fde8f8893233995964ecf09