apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: gtfs
          image: docker.io/vilibalchev5/gtfs:5f97218a40724f709580bba8ae60a93a6cfc5fd1