apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: loyalty
          image: docker.io/vilibalchev5/loyalty:5f97218a40724f709580bba8ae60a93a6cfc5fd1
