apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: loyalty
          image: docker.io/vilibalchev5/loyalty:80d361d77fddf16e189aa015a12c0367b266b548
