apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: loyalty
          image: docker.io/vilibalchev5/loyalty:3a726fcf6719eb221acc5f760a6e5c1e1adecabc
