apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gtfs-ingress
  namespace: services
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: cgmplus-dev.example.com
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 5000
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gtfs-service
                port:
                  number: 5000
