apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gtfs-app-secrets
  namespace: gtfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gtfs-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: gtfs
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: gtfs
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: gtfs
        property: POSTGRES_DB
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: gtfs
        property: POSTGRES_PORT
