apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-app-secrets
  namespace: gtfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: auth-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: SQLALCHEMY_DATABASE_URI
      remoteRef:
        key: auth
        property: SQLALCHEMY_DATABASE_URI
    - secretKey: JWT_SECRET
      remoteRef:
        key: auth
        property: JWT_SECRET
