apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loyalty-app-secrets
  namespace: services
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: loyalty-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: loyalty
        property: POSTGRES_PORT
    - secretKey: POSTGRES_DB
      remoteRef:
        key: loyalty
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: loyalty
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: loyalty
        property: POSTGRES_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: loyalty
        property: JWT_SECRET
