"""point transaction model

Revision ID: 986bc69ea79f
Revises: c17a6e5b0d94
Create Date: 2026-04-18 10:06:10.869487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986bc69ea79f'
down_revision = 'c17a6e5b0d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('pt_type', sa.Enum('transport', 'other', name='pt_typeenum'), nullable=False),
    sa.Column('ammount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_transaction_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_transaction_id'))

    op.drop_table('point_transaction')
    # ### end Alembic commands ###
