"""redemption model

Revision ID: c4e33d496627
Revises: 986bc69ea79f
Create Date: 2026-04-18 12:32:38.554717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e33d496627'
down_revision = '986bc69ea79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redemption_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redemption_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redemption_model_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redemption_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redemption_model_id'))

    op.drop_table('redemption_model')
    # ### end Alembic commands ###
