apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azurekv-backend
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: 420584ab-4eec-41c7-bb43-7364d0a6fdfd
      vaultUrl: https://cgmplusprodkv7048.vault.azure.net/
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets