apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loyalty-app-secrets
  namespace: services
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv-backend
  target:
    name: loyalty-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: loyalty-postgres-port
    - secretKey: POSTGRES_DB
      remoteRef:
        key: loyalty-postgres-db
    - secretKey: POSTGRES_USER
      remoteRef:
        key: loyalty-postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: loyalty-postgres-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: auth-jwt-secret
