apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cgmplus-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TUES-2026-PBL-11-klas/Colonel-Sanders-CGMplus.git
    targetRevision: development
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: gtfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
