apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: auth
          image: cgmplusprod.azurecr.io/auth-new:283f8da557c459edb8d910076855a073cd25ce82