apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: gtfs
          image: cgmplusprod.azurecr.io/gtfs:b331d9de7aec0fe8bec854b7002f10ae527bfcf3