apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: gtfs
          image: cgmplusprod.azurecr.io/gtfs:283f8da557c459edb8d910076855a073cd25ce82