apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: loyalty
          image: cgmplusprod.azurecr.io/loyalty:581da5522c018cd18f42a0907e760e2bd5818d4e
