apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: loyalty
          image: cgmplusprod.azurecr.io/loyalty:58381e1219ac66d118a9d705612ef2a1c350b96c
