apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  namespace: services
spec:
  template:
    spec:
      containers:
        - name: loyalty
          image: cgmplusprod.azurecr.io/loyalty:fcf9aa317fc147884cacf6f090be449a1da1bd3a
